### JSONRestAPI Configuration ###
# Thank you for downloading this plugin!
# I hope this isn't overly complicated, but if you run into issues, feel free to request support below:
# Discord: https://discord.gg/0kYlxgkh65QhZAjm
# GitHub Discussions: https://github.com/ChewMC/JSONRestAPI/discussions

# Made changes? Run /jrareload
# Requires jsonrestapi.reload or OP.

# The port to listen on.
## Some shared hosts don't handle this very well, so you may need to change this value.
## Only change this if you receive a "port in use" warning in your console on startup.
## Confused? Feel free to contact me above.
port: 6548

# An auth-key for private requests.
## Only takes effect if authkey: true in the routes below, plus the root route.
authkey: CHANGE_ME_PLEASE

# Debug mode
## Adds some useful debug output for developing.
## Includes the full request string, parameters, and route itself.
## Most of the time no one cares about this, but you might.
debug: false

# Route setup
## By default, the root route accept a raw POST value for any info not provided here.
## You can set up specific routes below.
## A GET request must not be player-specific, and can for example be to query the players online.
## A POST request must have a "username" or "uuid" parameter specified. Auth key is enabled by default for these.

routes:
  # The path to listen to. This must be lowercase.
  # Slashes are accepted, for example, ping/the_server
  # Do not include an initial slash, it is implied.
  # This one is /ping, for example.
  ping:
    # The placeholder to parse.
    # This runs the parse function on this string, so anything not in placeholders will render raw.
    response: Pong!
    # The method type, described above.
    method: GET
    # Whether or not to use an auth key, default false for GET.
    authkey: false
  # You can get a little bit more complicated, too.
  # The response is wrapped in JSON, but you can add your own, too!
  # The JSON isn't validated, so don't worry about issues there.
  # This one gets some basic server info. Requires the "Server" eCloud expansion.
  server/info:
    response: |
      {
        "name": "%server_name%",
        "tps": "%server_tps_1%",
        "online": "%server_online_players%"
      }
    method: GET
    authkey: false