name: JSONRestAPI
version: ${project.version}
main: pw.chew.jsonrestapi.JSONRestAPI
api-version: 1.16
depend: [PlaceholderAPI]
authors: [ Chew ]
description: A simple web server for receiving and parsing requests.
website: https://chew.pw/mc

commands:
  jrareload:
    description: Reloads the configuration.
    usage: "Usage: /jrareload"
    permission: jsonrestapi.reload
    permission-message: Only people with permission can reload, sorry!

permissions:
  jsonrestapi.reload:
    default: op